# Generates a C++ header that carries worker/src/index.js verbatim.
#
# There used to be two copies of the Worker: one in worker/src/index.js for
# `wrangler deploy`, and one pasted into src/Setup.cpp for the built-in
# deployer. They drifted - the embedded one had /resolve, the repo one did not,
# so a manual wrangler deploy silently broke the client's DNS. This script makes
# the repo file the only source and the C++ side a build artifact.
#
# Script mode:
#   cmake -DINPUT=<js> -DOUTPUT=<hpp> -P EmbedWorker.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "EmbedWorker.cmake requires -DINPUT=<file> and -DOUTPUT=<file>")
endif()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Worker source not found: ${INPUT}")
endif()

file(READ "${INPUT}" WORKER_JS)

# The delimiter that closes the C++ raw string must not occur in the payload.
set(RAW_DELIMITER "SPLITHELLOJS")
string(FIND "${WORKER_JS}" ")${RAW_DELIMITER}\"" DELIMITER_CLASH)
if(NOT DELIMITER_CLASH EQUAL -1)
    message(FATAL_ERROR
        "worker/src/index.js contains the raw-string delimiter )${RAW_DELIMITER}\" "
        "- change RAW_DELIMITER in cmake/EmbedWorker.cmake")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedWorker.cmake from worker/src/index.js.\n"
"// Do not edit: changes belong in worker/src/index.js.\n"
"#pragma once\n"
"\n"
"inline constexpr const char* kWorkerSource = R\"${RAW_DELIMITER}(${WORKER_JS})${RAW_DELIMITER}\";\n")
