# Embeds one UTF-8 text file into a generated C++ header.
#
# Script mode:
#   cmake -DINPUT=<file> -DOUTPUT=<hpp> -DVARIABLE=<identifier>
#         -DRAW_DELIMITER=<token> -P EmbedText.cmake

foreach(REQUIRED INPUT OUTPUT VARIABLE RAW_DELIMITER)
    if(NOT DEFINED ${REQUIRED})
        message(FATAL_ERROR "EmbedText.cmake requires -D${REQUIRED}=...")
    endif()
endforeach()

if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Embedded source not found: ${INPUT}")
endif()

file(READ "${INPUT}" SOURCE_TEXT)
string(FIND "${SOURCE_TEXT}" ")${RAW_DELIMITER}\"" DELIMITER_CLASH)
if(NOT DELIMITER_CLASH EQUAL -1)
    message(FATAL_ERROR
        "${INPUT} contains the raw-string delimiter )${RAW_DELIMITER}\"")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT}"
    "// Generated by cmake/EmbedText.cmake. Do not edit.\n"
    "#pragma once\n\n"
    "inline constexpr const char* ${VARIABLE} = R\"${RAW_DELIMITER}(${SOURCE_TEXT})${RAW_DELIMITER}\";\n")
